export const GET_POKEMONS = "GET_POKEMONS";
export const DELETE_POKEMON = "DELETE_POKEMON";
export const GET_POKEMON_BYNAME = "GET_POKEMON_BYNAME";
export const GET_POKEMON_ID = "GET_POKEMON_ID";
export const GET_TYPES = "GET_TYPES";
export const POST_POKEMON = "POST_POKEMON";
export const SET_PAGE = "SET_PAGE";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";