export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKEMON_BYNAME = "GET_POKEMON_BYNAME";
export const GET_POKEMON_ID = "GET_POKEMON_ID";
export const GET_TYPES = "GET_TYPES";
export const POST_POKEMON = "POST_POKEMON";